global using CleanArchitecture.Domain.Data;
global using CleanArchitecture.Domain.Entities;
global using CleanArchitecture.Migrations.Configuration;
global using CleanArchitecture.Migrations.Data;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Migrations;
global using Microsoft.Extensions.Configuration;
