global using CleanArchitecture.Domain.Entities;
global using CleanArchitecture.Domain.Repositories;
global using CleanArchitecture.Infrastructure.Repositories;
global using CleanArchitecture.Migrations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System;
global using System.Linq.Expressions;
